### ISSUE TITLE
browser-window dependency not found

### ISSUE THREAD

**Issue by mciparelli** [parro-it/electron-google-oauth#8]
You're attempting to use a `browser-window` dependency not specified in `package.json` so this library cannot be used because of this dependency not being found.
Nice work though! I like how you abstracted signin for electron apps.

**Comment by black-snow** [comment]
Leaving a comment to get notices when this is resolved. Would've loved to use this but can't for there is no `browser-window`.

**Comment by parro-it** [comment]
@mciparelli , @black-snow, Thank you for the issue!

`browser-window` is a core Electron module, and not an npm package, so it should not be listed in package.json deps.

However, recent electron releases has changed way `browser-window` should be required (it's now a property of `electron` core module). 

Please check out version 2.0 where I fixed this issue and also removed some deprecated argument in API...

**Comment by jwir3** [comment]
@parro-it Where is version 2.0? I don't see it in any of the published releases (tags), nor a release branch for it.
